[package]
name = "ferrite-rs"
version = "0.0.1-beta.2"
edition = "2021"

description = "An ML Library for fast and memorysafe inference."
license = "MIT"

[dependencies]
csv = "1.3.1"
matrixmultiply = "0.3.9"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.8.5"
